### ISSUE TITLE
Why dump ?

### ISSUE THREAD

**Issue by IlanZ93** [sponges/JavaMusicBot#1]
Hello i can see we can dump in a json a playlist, but what for ? We cant add this to the bot in the server

**Comment by sponges** [comment]
There for debugging purposes, I should make it loadable though.

**Comment by ducc** [comment]
Hey @IlanZ93 I just added a feature to load in these dumps! https://github.com/ducc/JavaMusicBot/commit/923ccd6041e1c156ea7d936ebe54a9127717d474

**Comment by IlanZ93** [comment]
Oh ! Thats a good News ! Nice good work :D
