### ISSUE TITLE
Need help with dabbot and the chat on my discord

### ISSUE THREAD

**Issue by Stefanse93** [sponges/JavaMusicBot#2]
Hello,

Is it possible to make it stop typing in chat whenever the next songs play in a queue? For example if a playlist of 10 songs is enabled then everytime the song changes it writes it in chat, is it possible to remove that feature? I still want it to type in chat whenever I do !!!help or choose a radio station or something.

Hope you can help!

**Comment by sponges** [comment]
Suggestions & questions belong on the dabBot support server: https://discord.gg/MFgsBAs
